# bug描述
运行nextflow，profile选择docker执行process时，在调用scanpy(1.10.2)时报以下错误：  
```
File "/usr/local/lib/python3.12/site-packages/numba/core/caching.py", line 337, in __init__
raise RuntimeError("cannot cache function %r: no locator available "
RuntimeError: cannot cache function 'sparse_mean_var_minor_axis': no locator available for file '/usr/local/lib/python3.12/site-packages/scanpy/preprocessing/_utils.py'
```

相同脚本，conda运行正常。

# 解决办法
上网搜索，猜测与镜像中 `numba` 环境变量中的缓存路径(`NUMBA_CACHE_DIR`)有关  

但是在镜像的环境变量中固定 `NUMBA_CACHE_DIR` 并没有解决问题

在 process 的script中添加得以解决

```
mkdir ./temp
chmod ugo+rwx -R ./temp
export NUMBA_CACHE_DIR="./temp"
```

# ref
- [numba Environment variables](https://numba.pydata.org/numba-doc/dev/reference/envvars.html)  
- [same  bug by others](https://github.com/zktuong/dandelion/issues/198)